const productos = [
	{
		id: 1,
		tipo: "plantas",
		nombre: "Aloe",
		descripcion: "Aloe Vera en maceta de cemento con plato de cemento. ",
		imagen: "/assets/productos/planta-1.jpg",
		precio: 1050,
		stock: 10,
	},
	{
		id: 2,
		tipo: "plantas",
		nombre: "Cereu",
		descripcion: "Cereu en maceta de cemento con plato de cemento.",
		imagen: "/assets/productos/planta-2.jpg",
		precio: 950,
		stock: 10,
	},
	{
		id: 3,
		tipo: "plantas",
		nombre: "Capitella",
		descripcion: "Capitella en maceta de cemento sin plato.",
		imagen: "/assets/productos/planta-3.jpg",
		precio: 700,
		stock: 8,
	},
	{
		id: 4,
		tipo: "plantas",
		nombre: "Set 3",
		descripcion: "set de 3 suculentas en macetas de cemento.",
		imagen: "/assets/productos/planta-4.jpg",
		precio: 1800,
		stock: 8,
	},
	{
		id: 5,
		tipo: "plantas",
		nombre: "Zebra",
		descripcion: "Zebra en maceta de cemento sin plato.",
		imagen: "/assets/productos/planta-5.jpg",
		precio: 1100,
		stock: 8,
	},
	{
		id: 6,
		tipo: "plantas",
		nombre: "Crassula",
		descripcion: "Crassula en maceta de cemento sin plato.",
		imagen: "/assets/productos/planta-6.jpg",
		precio: 950,
		stock: 10,
	},

	{
		id: 7,
		tipo: "cuadros",
		nombre: "Set x 3",
		descripcion: "Set de 3 cuadros de niños. Motivos: Animales y flores. Vinilo en bastidor de madera, medidas 25x44,5 cmts.",
		imagen: "/assets/productos/cuadro-1.jpg",
		precio: 2000,
		stock: 5,
	},
	{
		id: 8,
		tipo: "cuadros",
		nombre: "Cuadro",
		descripcion: "Cuadro de 25x44cmts con frase. Vinilo en bastidor de madera, medida 25x44,5 cmts.",
		imagen: "/assets/productos/cuadro-2.jpg",
		precio: 900,
		stock: 5,
	},
	{
		id: 9,
		tipo: "cuadros",
		nombre: "Set x 3",
		descripcion: "Set de 3 cuadros de plantas en compose. Vinilo en bastidor de madera, medidas 25x44,5 cmts.",
		imagen: "/assets/productos/cuadro-3.jpg",
		precio: 2000,
		stock: 5,
	},
	{
		id: 10,
		tipo: "cuadros",
		nombre: "Set x 2",
		descripcion: "Set de 2 cuadros, 1 cuadrado (25x25 cmts) y 1 rectangular (25x44,5 cmts). Imagen y frase.",
		imagen: "/assets/productos/cuadro-4.jpg",
		precio: 1500,
		stock: 10,
	},
	{
		id: 11,
		tipo: "cuadros",
		nombre: "Set x 2",
		descripcion: "Set de 2 cuadros cuadrados. Para niños motivo animales. Vinilo en bastidor de madera, medidas 25x25 cmts.",
		imagen: "/assets/productos/cuadro-5.jpg",
		precio: 1300,
		stock: 10,
	},
	{
		id: 12,
		tipo: "cuadros",
		nombre: "Set x 2",
		descripcion: "Set de 2 cuadros, motivos varios. Vinilo en bastidor de madera, medidas 25x25 cmts.",
		imagen: "/assets/productos/cuadro-6.jpg",
		precio: 1300,
		stock: 7,
	},

	{
		id: 13,
		tipo: "macetas",
		nombre: "Maceta 1",
		descripcion: "Maceta de cemento número 1. Tamaño 30x8.5cmts",
		imagen: "/assets/productos/maceta-1.jpg",
		precio: 2000,
		stock: 7,
	},
	{
		id: 14,
		tipo: "macetas",
		nombre: "Maceta 2",
		descripcion: "Maceta de cemento número 2. Tamaño 17x7.5cmts",
		imagen: "/assets/productos/maceta-2.jpg",
		precio: 1500,
		stock: 8,
	},
	{
		id: 15,
		tipo: "macetas",
		nombre: "Maceta 3",
		descripcion: "Maceta de cemento número 3. Tamaño 25x19cmts",
		imagen: "/assets/productos/maceta-3.jpg",
		precio: 1250,
		stock: 7,
	},
	{
		id: 16,
		tipo: "macetas",
		nombre: "Maceta 4",
		descripcion: "Maceta de cemento número 4. Tamaño 19x15 cmts",
		imagen: "/assets/productos/maceta-4.jpg",
		precio: 1000,
		stock: 7,
	},
	{
		id: 17,
		tipo: "macetas",
		nombre: "Maceta 5",
		descripcion: "Maceta de cemento número 5. Tamaño 10x10 cmts",
		imagen: "/assets/productos/maceta-5.jpg",
		precio: 800,
		stock: 7,
	},
	{
		id: 18,
		tipo: "macetas",
		nombre: "Maceta 6",
		descripcion: "Maceta de cemento número 6. Tamaño 10x8 cmts",
		imagen: "/assets/productos/maceta-6.jpg",
		precio: 600,
		stock: 10,
	},
	{
		id: 19,
		tipo: "vinilos",
		nombre: "Vinilo 1",
		descripcion: "Vinilo transparente adhesivo para botella. Medidas 9x12 cmts.",
		imagen: "/assets/productos/vinilo-1.jpg",
		precio: 200,
		stock: 10,
	},
	{
		id: 20,
		tipo: "vinilos",
		nombre: "Vinilo 2",
		descripcion: "Vinilo transparente adhesivo para botella. Medidas 9x12 cmts.",
		imagen: "/assets/productos/vinilo-2.jpg",
		precio: 200,
		stock: 9,
	},
	{
		id: 21,
		tipo: "vinilos",
		nombre: "Vinilo 3",
		descripcion: "Vinilo transparente adhesivo para botella. Medidas 9x12 cmts.",
		imagen: "/assets/productos/vinilo-3.jpg",
		precio: 200,
		stock: 9,
	},
	{
		id: 22,
		tipo: "vinilos",
		nombre: "Vinilo 4",
		descripcion: "Vinilos adhesivos, redondos tamaño 5cmts.",
		imagen: "/assets/productos/vinilo-4.jpg",
		precio: 80,
		stock: 9,
	},
	{
		id: 23,
		tipo: "vinilos",
		nombre: "Vinilo 5",
		descripcion: "Vinilos adhesivos, cuadrados medidas 7x7cm.",
		imagen: "/assets/productos/vinilo-5.jpg",
		precio: 100,
		stock: 19,
	},
	{
		id: 24,
		tipo: "vinilos",
		nombre: "Vinilo 6",
		descripcion: "Vinilos adhesivos, cuadrados medidas 7x7cm.",
		imagen: "/assets/productos/vinilo-6.jpg",
		precio: 100,
		stock: 20,
	},
];

export const getFetch = new Promise((resolve, reject) => {
	setTimeout(() => {
		resolve(productos);
	}, 2000);
});
